version: '3'
services:
  supervisor:
    build: ./Supervisor
    ports:
      - "8080:8080"
    environment:
      - WORKER_INFO_DATABASE_URL=postgres://admin:admin@worker-info-db:5432/worker-info?sslmode=disable
      - JOB_INFO_DATABASE_URL=postgres://admin:admin@job-info-db:5433/job-info?sslmode=disable
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./Supervisor:/app
    depends_on:
      - worker-info-db
      - job-info-db
      - scraping-data-db
      - redis

  worker:
    build: ./Worker
    environment:
      - SCRAPING_DATA_DATABASE_URL=postgres://admin:admin@scraping-data-db:5434/scraping-data?sslmode=disable
      - JOB_INFO_DATABASE_URL=postgres://admin:admin@job-info-db:5433/job-info?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - SUPERVISOR_GRPC_ADDRESS=supervisor:50051
    volumes:
      - ./Worker:/app
    depends_on:
      - worker-info-db
      - job-info-db
      - scraping-data-db
      - redis

  worker-info-db:
    image: postgres
    container_name: worker-info-db
    environment:
      POSTGRES_DB: worker-info
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5432
    volumes:
      - worker-info-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  job-info-db:
    image: postgres
    container_name: job-info-db
    environment:
      POSTGRES_DB: job-info
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5433
    volumes:
      - job-info-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5433:5433"

  scraping-data-db:
    image: postgres
    container_name: scraping-data-db
    environment:
      POSTGRES_DB: scraping-data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5434
    volumes:
      - scraping-data-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5434:5434"

  redis:
    image: redis:alpine
    container_name: redis-job-queue
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - worker-info-db
      - job-info-db
      - scraping-data-db
    restart: unless-stopped

volumes:
  worker-info-data:
  job-info-data:
  scraping-data-data:
  redis-data:
  pgadmin-data:

    
