// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/supervisor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_supervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RegisterWorkerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_supervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,4,opt,name=memoryUsage,proto3" json:"memoryUsage,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthHeartbeatRequest) Reset() {
	*x = HealthHeartbeatRequest{}
	mi := &file_proto_supervisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthHeartbeatRequest) ProtoMessage() {}

func (x *HealthHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HealthHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{2}
}

func (x *HealthHeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HealthHeartbeatRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthHeartbeatRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HealthHeartbeatRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HealthHeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HealthHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthHeartbeatResponse) Reset() {
	*x = HealthHeartbeatResponse{}
	mi := &file_proto_supervisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthHeartbeatResponse) ProtoMessage() {}

func (x *HealthHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HealthHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{3}
}

func (x *HealthHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthHeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompletionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	JobName       string                 `protobuf:"bytes,2,opt,name=jobName,proto3" json:"jobName,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UrlSeedSearch string                 `protobuf:"bytes,4,opt,name=urlSeedSearch,proto3" json:"urlSeedSearch,omitempty"`
	LastResult    string                 `protobuf:"bytes,5,opt,name=lastResult,proto3" json:"lastResult,omitempty"`
	Cron          string                 `protobuf:"bytes,6,opt,name=cron,proto3" json:"cron,omitempty"`
	LastRun       string                 `protobuf:"bytes,7,opt,name=lastRun,proto3" json:"lastRun,omitempty"`
	NextRun       string                 `protobuf:"bytes,8,opt,name=nextRun,proto3" json:"nextRun,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=isActive,proto3" json:"isActive,omitempty"`
	WorkerId      string                 `protobuf:"bytes,10,opt,name=workerId,proto3" json:"workerId,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionStatusRequest) Reset() {
	*x = CompletionStatusRequest{}
	mi := &file_proto_supervisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionStatusRequest) ProtoMessage() {}

func (x *CompletionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionStatusRequest.ProtoReflect.Descriptor instead.
func (*CompletionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{4}
}

func (x *CompletionStatusRequest) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *CompletionStatusRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CompletionStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CompletionStatusRequest) GetUrlSeedSearch() string {
	if x != nil {
		return x.UrlSeedSearch
	}
	return ""
}

func (x *CompletionStatusRequest) GetLastResult() string {
	if x != nil {
		return x.LastResult
	}
	return ""
}

func (x *CompletionStatusRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CompletionStatusRequest) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *CompletionStatusRequest) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

func (x *CompletionStatusRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CompletionStatusRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompletionStatusRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CompletionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionStatusResponse) Reset() {
	*x = CompletionStatusResponse{}
	mi := &file_proto_supervisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionStatusResponse) ProtoMessage() {}

func (x *CompletionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionStatusResponse.ProtoReflect.Descriptor instead.
func (*CompletionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{5}
}

func (x *CompletionStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompletionStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_supervisor_proto protoreflect.FileDescriptor

const file_proto_supervisor_proto_rawDesc = "" +
	"\n" +
	"\x16proto/supervisor.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x15RegisterWorkerRequest\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostName\x18\x02 \x01(\tR\bhostName\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa8\x01\n" +
	"\x16HealthHeartbeatRequest\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bcpuUsage\x18\x03 \x01(\x01R\bcpuUsage\x12 \n" +
	"\vmemoryUsage\x18\x04 \x01(\x01R\vmemoryUsage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"M\n" +
	"\x17HealthHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe5\x02\n" +
	"\x17CompletionStatusRequest\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\x05R\x05jobId\x12\x18\n" +
	"\ajobName\x18\x02 \x01(\tR\ajobName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12$\n" +
	"\rurlSeedSearch\x18\x04 \x01(\tR\rurlSeedSearch\x12\x1e\n" +
	"\n" +
	"lastResult\x18\x05 \x01(\tR\n" +
	"lastResult\x12\x12\n" +
	"\x04cron\x18\x06 \x01(\tR\x04cron\x12\x18\n" +
	"\alastRun\x18\a \x01(\tR\alastRun\x12\x18\n" +
	"\anextRun\x18\b \x01(\tR\anextRun\x12\x1a\n" +
	"\bisActive\x18\t \x01(\bR\bisActive\x12\x1a\n" +
	"\bworkerId\x18\n" +
	" \x01(\tR\bworkerId\x12<\n" +
	"\vcompletedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"N\n" +
	"\x18CompletionStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x94\x02\n" +
	"\x11SupervisorService\x12M\n" +
	"\x0eRegisterWorker\x12\x1c.proto.RegisterWorkerRequest\x1a\x1d.proto.RegisterWorkerResponse\x12X\n" +
	"\x15HealthHeartbeatStream\x12\x1d.proto.HealthHeartbeatRequest\x1a\x1e.proto.HealthHeartbeatResponse(\x01\x12V\n" +
	"\x13LogCompletionStatus\x12\x1e.proto.CompletionStatusRequest\x1a\x1f.proto.CompletionStatusResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_supervisor_proto_rawDescOnce sync.Once
	file_proto_supervisor_proto_rawDescData []byte
)

func file_proto_supervisor_proto_rawDescGZIP() []byte {
	file_proto_supervisor_proto_rawDescOnce.Do(func() {
		file_proto_supervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_supervisor_proto_rawDesc), len(file_proto_supervisor_proto_rawDesc)))
	})
	return file_proto_supervisor_proto_rawDescData
}

var file_proto_supervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_supervisor_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),    // 0: proto.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),   // 1: proto.RegisterWorkerResponse
	(*HealthHeartbeatRequest)(nil),   // 2: proto.HealthHeartbeatRequest
	(*HealthHeartbeatResponse)(nil),  // 3: proto.HealthHeartbeatResponse
	(*CompletionStatusRequest)(nil),  // 4: proto.CompletionStatusRequest
	(*CompletionStatusResponse)(nil), // 5: proto.CompletionStatusResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_proto_supervisor_proto_depIdxs = []int32{
	6, // 0: proto.CompletionStatusRequest.completedAt:type_name -> google.protobuf.Timestamp
	0, // 1: proto.SupervisorService.RegisterWorker:input_type -> proto.RegisterWorkerRequest
	2, // 2: proto.SupervisorService.HealthHeartbeatStream:input_type -> proto.HealthHeartbeatRequest
	4, // 3: proto.SupervisorService.LogCompletionStatus:input_type -> proto.CompletionStatusRequest
	1, // 4: proto.SupervisorService.RegisterWorker:output_type -> proto.RegisterWorkerResponse
	3, // 5: proto.SupervisorService.HealthHeartbeatStream:output_type -> proto.HealthHeartbeatResponse
	5, // 6: proto.SupervisorService.LogCompletionStatus:output_type -> proto.CompletionStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_supervisor_proto_init() }
func file_proto_supervisor_proto_init() {
	if File_proto_supervisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_supervisor_proto_rawDesc), len(file_proto_supervisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_supervisor_proto_goTypes,
		DependencyIndexes: file_proto_supervisor_proto_depIdxs,
		MessageInfos:      file_proto_supervisor_proto_msgTypes,
	}.Build()
	File_proto_supervisor_proto = out.File
	file_proto_supervisor_proto_goTypes = nil
	file_proto_supervisor_proto_depIdxs = nil
}
