// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/supervisor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_supervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RegisterWorkerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_supervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_supervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_supervisor_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_supervisor_proto protoreflect.FileDescriptor

const file_proto_supervisor_proto_rawDesc = "" +
	"\n" +
	"\x16proto/supervisor.proto\x12\x05proto\"c\n" +
	"\x15RegisterWorkerRequest\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostName\x18\x02 \x01(\tR\bhostName\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2b\n" +
	"\x11SupervisorService\x12M\n" +
	"\x0eRegisterWorker\x12\x1c.proto.RegisterWorkerRequest\x1a\x1d.proto.RegisterWorkerResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_supervisor_proto_rawDescOnce sync.Once
	file_proto_supervisor_proto_rawDescData []byte
)

func file_proto_supervisor_proto_rawDescGZIP() []byte {
	file_proto_supervisor_proto_rawDescOnce.Do(func() {
		file_proto_supervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_supervisor_proto_rawDesc), len(file_proto_supervisor_proto_rawDesc)))
	})
	return file_proto_supervisor_proto_rawDescData
}

var file_proto_supervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_supervisor_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),  // 0: proto.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 1: proto.RegisterWorkerResponse
}
var file_proto_supervisor_proto_depIdxs = []int32{
	0, // 0: proto.SupervisorService.RegisterWorker:input_type -> proto.RegisterWorkerRequest
	1, // 1: proto.SupervisorService.RegisterWorker:output_type -> proto.RegisterWorkerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_supervisor_proto_init() }
func file_proto_supervisor_proto_init() {
	if File_proto_supervisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_supervisor_proto_rawDesc), len(file_proto_supervisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_supervisor_proto_goTypes,
		DependencyIndexes: file_proto_supervisor_proto_depIdxs,
		MessageInfos:      file_proto_supervisor_proto_msgTypes,
	}.Build()
	File_proto_supervisor_proto = out.File
	file_proto_supervisor_proto_goTypes = nil
	file_proto_supervisor_proto_depIdxs = nil
}
