// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/supervisor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupervisorService_RegisterWorker_FullMethodName = "/proto.SupervisorService/RegisterWorker"
)

// SupervisorServiceClient is the client API for SupervisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SupervisorService defines RPCs that the Worker calls on the Supervisor
// Supervisor -> receives these calls from Worker
type SupervisorServiceClient interface {
	// RegisterWorker registers a new worker with the supervisor
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
}

type supervisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupervisorServiceClient(cc grpc.ClientConnInterface) SupervisorServiceClient {
	return &supervisorServiceClient{cc}
}

func (c *supervisorServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, SupervisorService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServiceServer is the server API for SupervisorService service.
// All implementations must embed UnimplementedSupervisorServiceServer
// for forward compatibility.
//
// SupervisorService defines RPCs that the Worker calls on the Supervisor
// Supervisor -> receives these calls from Worker
type SupervisorServiceServer interface {
	// RegisterWorker registers a new worker with the supervisor
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	mustEmbedUnimplementedSupervisorServiceServer()
}

// UnimplementedSupervisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupervisorServiceServer struct{}

func (UnimplementedSupervisorServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedSupervisorServiceServer) mustEmbedUnimplementedSupervisorServiceServer() {}
func (UnimplementedSupervisorServiceServer) testEmbeddedByValue()                           {}

// UnsafeSupervisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupervisorServiceServer will
// result in compilation errors.
type UnsafeSupervisorServiceServer interface {
	mustEmbedUnimplementedSupervisorServiceServer()
}

func RegisterSupervisorServiceServer(s grpc.ServiceRegistrar, srv SupervisorServiceServer) {
	// If the following call pancis, it indicates UnimplementedSupervisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupervisorService_ServiceDesc, srv)
}

func _SupervisorService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupervisorService_ServiceDesc is the grpc.ServiceDesc for SupervisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupervisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SupervisorService",
	HandlerType: (*SupervisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _SupervisorService_RegisterWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/supervisor.proto",
}
